// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Ih9350hfeDjZPiDWtSLERsMwvTxdPk8',
    appId: '1:109066027840:web:61a2465ec06c5c5e7cf0a5',
    messagingSenderId: '109066027840',
    projectId: 'lupe-ac734',
    authDomain: 'lupe-ac734.firebaseapp.com',
    storageBucket: 'lupe-ac734.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqn-VyPiVHuGQSiMDNbPf6Ex38lrVZUk',
    appId: '1:109066027840:android:5496737901c6f2a37cf0a5',
    messagingSenderId: '109066027840',
    projectId: 'lupe-ac734',
    storageBucket: 'lupe-ac734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9O1cuh4brrCWcBFXNZ7CjIp2z2rMnQY',
    appId: '1:109066027840:ios:684118ba9f3101d67cf0a5',
    messagingSenderId: '109066027840',
    projectId: 'lupe-ac734',
    storageBucket: 'lupe-ac734.appspot.com',
    iosBundleId: 'com.cristiantabares.lupe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK9O1cuh4brrCWcBFXNZ7CjIp2z2rMnQY',
    appId: '1:109066027840:ios:d756db06e6e6d8087cf0a5',
    messagingSenderId: '109066027840',
    projectId: 'lupe-ac734',
    storageBucket: 'lupe-ac734.appspot.com',
    iosBundleId: 'com.cristiantabares.lupe.RunnerTests',
  );
}
